POST http://localhost:3001/api/orders HTTP/1.1
Content-type: application/json

{
  "customerId": "603df0abf371a74c1662f609",
  "cart": [
    {
      "product": "6038d37d7560af5fba6dd4e8",
      "count": 5
    }
  ]
}